repository:
   description: Gnome Unstable repository
build:
  emerge:
    split_install: 1
  overlays:
    - gnome
  target:
    - gnome-extra/gnome-shell-extensions::gnome
    - gnome-base/gnome-extra-apps::gnome
    - gnome-base/gnome-shell::gnome
    - gnome-base/gdm::gnome
    - gnome-base/gnome-core-apps::gnome
    - gnome-base/gnome-core-libs::gnome
    - x11-wm/mutter::gnome
