repository:
   description: Haskell repository
   maintenance:

build:

  equo:
    repository: weekly

    # Don't use entropy for dependencies, as it will pull Haskell libraries compiled against the wrong version of GHC.
    dependency_install:
        enable: 0

  overlays:
    - haskell

  target:
    - '>=app-emacs/ghc-mod-5.8.0.0-r2'
    - app-portage/hackport
    - dev-haskell/hasktags
    - dev-haskell/hdevtools
    - dev-haskell/hlint
    - dev-haskell/hpack
    - dev-haskell/optparse-simple
    - dev-haskell/stack
    - dev-haskell/yaml
    - dev-lang/ghc

