repository:
   description: Devel channel repository
build:
  script:
    pre:
      - gcc-config x86_64-pc-linux-gnu-4.9.3-vanilla
    post:
      - gcc-config x86_64-pc-linux-gnu-4.9.3-vanilla
  qa_checks: 1
  emerge:
    # Install each package separately
    split_install: 1
    default_args: --accept-properties=-interactive -t --verbose --nospinner --oneshot --complete-graph --buildpkg
    features: assume-digests binpkg-logs -userpriv config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync parallel-fetch preserve-libs protect-owned sandbox sfperms splitdebug strict
  overlays:
    - kde
  target:
    - sys-apps/systemd::sabayon-distro
    - =sys-kernel/genkernel-next-9999
    - =app-admin/calamares-9999
    - sys-kernel/linux-sabayon[dracut]
    - sys-devel/gcc::sabayon-distro[-gcj,-go]
    - sys-devel/base-gcc::sabayon-distro[-gcj,-go]
