repository:
   description: Elementary repository
build:
  emerge:
    features: assume-digests binpkg-logs -userpriv config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync parallel-fetch preserve-libs protect-owned sandbox sfperms splitdebug strict -sandbox
    split_install: 1
  overlays:
    - elementary  
  target:
    - x11-misc/lightdm::elementary
    - net-misc/networkmanager::elementary
    - pantheon-base/wingpanel::elementary
    - pantheon-base/pantheon-shell::elementary 

