repository:
  description: Sihnon server packages

  maintenance:
    remove:
      # www-apacge/mpm_itk depdendency is missing and breaking the build
      # Remove from the repository and re-add once clean
      - app-backup/backuppc
      # Blocks mysql
      - dev-db/mariadb-galera

build:
  emerge:
    # Install each package separately
    split_install: 1

    # Use sihnon overlay
    remote_overlay:
      - sihnon|git|https://github.com/optiz0r/gentoo-overlay.git

  equo:
    repositories:
      - sihnon-common

    dependency_install:
      prune_virtuals: 1

    package:
      mask:
        - dev-db/mariadb-galera

  # Use ebuilds from the following layman overlays
  overlays:
    - awesome
    - barzog-overlay
    - emery
    - fkmclane
    - flavour
    - gitlab

  # Packages to be built in this repo
  target:
    - app-admin/puppetdb
    - app-admin/puppetserver
    #- app-backup/backuppc
    - dev-db/phppgadmin
    - dev-db/phpmyadmin
    - dev-libs/libgit2::gentoo
    - dev-util/gitlab-ci-multi-runner-bin
    - dev-vcs/gitlab-shell::gitlab
    - media-video/motion
    - =net-irc/quassel-core-9999::sihnon
    - net-nds/phpldapadmin::gentoo
    - net-p2p/deluge
    - net-wireless/eyefiserver::sihnon
    - net-wireless/unifi
    - sys-apps/entropybroker::emery
    - www-apps/cgit
    - www-apps/dokuwiki
    - www-apps/gitlabhq::gitlab
    - www-apps/piwik
    - www-apps/wordpress
    - www-misc/motioneye::sihnon
    - www-misc/shellinabox
    - www-servers/gitlab-workhorse::gitlab

# vim: set ts=2 shiftwidth=2 expandtab :

