repository:
  description: Sihnon server packages

  maintenance:
    remove:
      - net-irc/quassel-core
      
build:
  emerge:
    # Install each package separately
    split_install: 1
    remove:
      - =net-irc/quassel-core-9999

  equo:
    repositories:
      - sihnon-common

    dependency_install:
      prune_virtuals: 1

    package:
      mask:
        - dev-db/mariadb-galera
      remove:
        - net-analyzer/nagios-core
        - =net-irc/quassel-core-9999

  # Use ebuilds from the following layman overlays
  overlays:
    - awesome
    - barzog-overlay
    - fkmclane
    - flavour
    - gitlab
    - mrueg
    - sihnon
    - raw

  # Packages to be built in this repo
  target:
    - app-admin/puppetdb
    - app-admin/puppetserver
    #- app-backup/backuppc
    - dev-db/phppgadmin
    - dev-db/phpmyadmin
    - dev-libs/libgit2::gentoo
    - dev-util/gitlab-ci-multi-runner
    - dev-vcs/gitlab-shell
    - media-video/motion
    - net-analyzer/icinga
    - net-analyzer/icinga-web
    - net-irc/quassel-core::sabayon-distro
    - net-nds/phpldapadmin::gentoo
    - net-p2p/deluge
    - net-wireless/eyefiserver::sihnon
    - net-wireless/unifi
    - sys-apps/entropybroker::sihnon
    - www-apps/cgit
    - www-apps/dokuwiki
    - www-apps/gitlabhq::gitlab
    - www-apps/icingaweb2
    - www-apps/piwik
    - www-apps/wordpress
    - www-misc/motioneye::sihnon
    - www-misc/shellinabox
    - www-servers/gitlab-workhorse::gitlab

# vim: set ts=2 shiftwidth=2 expandtab :

