repository:
  description: Sihnon server packages
  
  #maintenance:
  #  clean_cache: 1

build:
  emerge:
    # Install each package separately
    split_install: 1
    preserved_rebuild: 1

  equo:
    repositories:
      - sihnon-common

    dependency_install:
      prune_virtuals: 1

    package:
      mask:
        - dev-db/mariadb-galera
      remove:
        - dev-db/libdbi-drivers
        - net-analyzer/icinga

  # Use ebuilds from the following layman overlays
  overlays:
    - awesome
    - barzog-overlay
    - fkmclane
    - flavour
    - gitlab
    - mrueg
    - pentoo
    - sihnon
    - raw

  injected_target:
    - dev-ruby/puppetdb-termini

  # Packages to be built in this repo
  target:
    #- app-backup/backuppc
    - dev-db/phppgadmin
    - dev-db/phpmyadmin
    - dev-util/gitlab-ci-multi-runner
    - dev-ruby/oxidized
    - dev-ruby/oxidized-fetch
    - dev-ruby/oxidized-script
    - dev-ruby/oxidized-web
    - dev-ruby/puppetdb-termini
    - net-analyzer/icinga
    - net-analyzer/icinga-web
    - net-dns/bind-dyndb-ldap
    - net-irc/quassel-core::sabayon-distro
    - net-misc/memcached::gentoo
    - net-nds/gss-proxy::gentoo
    - net-nds/phpldapadmin::gentoo
    - net-p2p/deluge
    - net-wireless/eyefiserver::sihnon
    - net-wireless/unifi
    - www-apps/cgit
    - www-apps/dokuwiki
    - www-apps/icingaweb2
    - www-apps/kibana-bin
    - www-apps/piwik
    - www-apps/wordpress
    - www-misc/shellinabox

# vim: set ts=2 shiftwidth=2 expandtab :

