repository:
  description: Sihnon server packages
  
  maintenance:
    clean_cache: 1

build:
  script:
    pre:
      - eselect python set python3.5

  emerge:
    # Install each package separately
    split_install: 1
    preserved_rebuild: 1

  equo:
    repositories:
      - sihnon-common

    dependency_install:
      prune_virtuals: 1

    package:
      mask:
        - dev-db/mariadb-galera
        
      install:
        # Ensure latest version to avoid slot conflict when updating qtsql
        - dev-qt/qtcore
      remove:
        - net-analyzer/nagios-core
        # Work around missing package from repo
        - dev-qt/qtsql
        # Switch from quassel-core to monolithic package which is more up to date
        - net-irc/quassel-core

  # Use ebuilds from the following layman overlays
  overlays:
    - awesome
    - barzog-overlay
    - defiance
    - fkmclane
    - flavour
    - funtoo
    - gitlab
    - mrueg
    - pentoo
    - sihnon
    - raw

  injected_target:
    - dev-ruby/puppetdb-termini
    - dev-qt/qtsql

  # Packages to be built in this repo
  target:
    #- app-backup/backuppc
    - dev-db/phppgadmin
    - dev-db/phpmyadmin
    - dev-qt/qtsql
    - dev-ruby/puppetdb-termini
    - net-analyzer/icinga
    - net-analyzer/icinga2
    - net-analyzer/icinga-web
    - net-dns/bind-dyndb-ldap
    - net-irc/quassel
    - net-misc/memcached::gentoo
    - net-nds/gss-proxy::gentoo
    - net-nds/phpldapadmin::gentoo
    - net-p2p/deluge
    - net-wireless/eyefiserver::sihnon
    - net-wireless/unifi
    - www-apps/cgit
    - www-apps/dokuwiki
    - www-apps/icingaweb2
    - www-apps/kibana-bin
    - www-apps/piwik
    - www-apps/wordpress
    - www-misc/shellinabox

# vim: set ts=2 shiftwidth=2 expandtab :

