repository:
   description: Testing repository
build:
  emerge:
    remote_overlay:
       - fsociety|git|https://github.com/z1lt0id/fs0ciety.git
  overlays:
    - elementary  
  target:
    - pantheon-base/pantheon-shell::elementary 
    - x11-apps/neofetch::fsociety

