repository:
   description: MATE Unstable repository
build:
  qa_checks: 1
  emerge:
    split_install: 1
    default_args: --accept-properties=-interactive -t --verbose --nospinner --oneshot --complete-graph --buildpkg
  overlays:
    - gentoo-mate
  target:
    - mate-base/mate::gentoo-mate[-gtk3]
    - mate-base/mate::gentoo-mate[gtk3]
