repository:
   description: KDE Unstable repository
build:
  emerge:
    split_install: 1
  equo:
    package:
      remove:
        # These packages conflict with plasma-desktop-9999
        - kde-plasma/kactivitymanagerd
        - kde-plasma/kactivities-workspace
  overlays:
    - kde
    - qt
  target:
    - kde-plasma/plasma-meta::kde
    - dev-qt/qtsvg::qt
    - dev-qt/qtimageformats::qt
    - dev-qt/qtchooser::qt
    - dev-qt/qttranslations::qt
    - dev-qt/qtpositioning::qt
    - dev-qt/qtnetwork::qt
    - dev-qt/qtx11extras::qt
    - dev-qt/qttest::qt
    - dev-qt/qtscript::qt
    - dev-qt/qdoc::qt
    - dev-qt/qtspeech::qt
    - dev-qt/linguist-tools::qt
    - dev-qt/qtquickcontrols::qt
    - dev-qt/qdbusviewer::qt
    - dev-qt/qtwebengine::qt
    - dev-qt/qtwidgets::qt
    - dev-qt/qtpaths::qt
    - dev-qt/qtdeclarative::qt
    - dev-qt/qtlocation::qt
    - dev-qt/qtxmlpatterns::qt
    - dev-qt/qtquick1::qt
    - dev-qt/qtsensors::qt
    - dev-qt/designer::qt
    - dev-qt/qtsql::qt
    - dev-qt/qtopengl::qt
    - dev-qt/linguist::qt
    - dev-qt/assistant::qt
    - dev-qt/qtwebchannel::qt
    - dev-qt/qdbus::qt
    - dev-qt/qtwebkit::qt
    - dev-qt/qtgraphicaleffects::qt
    - dev-qt/qtconcurrent::qt
    - dev-qt/qt-creator::qt
    - dev-qt/qtgui::qt
    - dev-qt/qtdiag::qt
    - dev-qt/qthelp::qt
    - dev-qt/qtwayland::qt
    - dev-qt/qtserialport::qt
    - dev-qt/qtmultimedia::qt
    - dev-qt/pixeltool::qt
    - dev-qt/qtcore::qt
    - dev-qt/qt3d::qt
    - dev-qt/qtbluetooth::qt
    - dev-qt/qtwebsockets::qt
    - dev-qt/qtxml::qt
    - dev-qt/qtdbus::qt
    - dev-qt/qtprintsupport::qt
    - =dev-util/kdevelop-5.0.9999::kde
