repository:
   description: KDE Unstable repository
build:
  emerge:
    split_install: 1
  equo:
    package:
      remove:
        # These packages conflict with plasma-desktop-9999
        - kde-plasma/kactivitymanagerd
        - kde-plasma/kactivities-workspace
  overlays:
    - kde
  target:
    - kde-plasma/plasma-meta::kde
