repository:
   description: KDE Unstable repository
build:
  emerge:
    split_install: 1
    default_args: --accept-properties=-interactive -t --verbose --nospinner --oneshot --complete-graph --buildpkg
  equo:
    package:
      remove:
        # These packages conflict with plasma-desktop-9999
        - kde-plasma/kactivitymanagerd
        - kde-plasma/kactivities-workspace
  overlays:
    - kde
  target:
    - kde-apps/kdepim-meta::kde
    - kde-plasma/plasma-meta::kde
    - =dev-util/kdevelop-9999::kde
