repository:
   description: Elementary repository  
build:
  emerge:
    features: assume-digests binpkg-logs -userpriv config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync parallel-fetch preserve-libs protect-owned sandbox sfperms splitdebug strict -sandbox -usersandbox
    split_install: 1
  overlays:
    - elementary 
    - sabayon-distro
  equo:
    package:
      remove:
        - x11-misc/lightdm-qt4
        - x11-misc/lightdm-base
  target:
    - x11-misc/lightdm::elementary
    - net-misc/networkmanager::elementary
    - pantheon-base/wingpanel::elementary
    - pantheon-base/pantheon-shell::elementary 

