repository:
   description: Haskell repository
   maintenance:
build:
  overlays:
    - haskell
  target:
    - app-emacs/ghc-mod
    - app-portage/hackport
    - dev-haskell/hasktags
    - dev-haskell/hdevtools
    - dev-haskell/hlint
    - dev-haskell/hpack
    - dev-haskell/optparse-simple
    - dev-haskell/stack
    - dev-haskell/yaml
    - dev-lang/ghc
  equo:
    # Don't use entropy for dependencies, as it will pull Haskell libraries compiled against the wrong version of GHC.
    dependency_install:
        enable: 0

    repository: weekly

