repository:
  description: Dotnet packages
#  maintenance:
#    clean_cache: 1

build:
  overlays:
    - dotnet
    - shnurise

  emerge:
    split_install: 1

  # Packages to be built in this repo
  target:
    - 'dev-lang/mono::dotnet'
    - 'dev-util/nunit'
    - 'dev-util/mono-packaging-tools'
    - 'dev-lang/ironscheme'
    - 'dev-lang/oscript'
    - 'dev-dotnet/npgsql' 
    - 'dev-util/gplex-dbremner'
    - 'dev-util/gppg-dbremner'
    - 'app-shells/pash'
    - 'dev-util/monodevelop::dotnet'
    - 'www-servers/xsp::dotnet'
    - 'www-apache/mod_mono::dotnet'
    - '\<net-irc/smuxi-9000'
    - 'media-gfx/pinta'
    - 'app-editors/mypad'
    - 'www-apps/orchard-cms'

  equo:
    dependency_install:
      prune_virtuals: 1
