repository:
  description: Pantheon Desktop Repository
build:
  emerge:
    # Install each package separately
    split_install: 1
    features: assume-digests binpkg-logs -collision-detect compressdebug config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync news parallel-fetch preserve-libs -protect-owned -sandbox sfperms splitdebug strict unknown-features-warn unmerge-logs unmerge-orphans userfetch usersandbox usersync xattr -userpriv
  overlays:
    - elementary
    - gnome-next
    - unity-gentoo
  target:
    - dev-lang/vala::gnome-next
    - pantheon-base/cerbere
    - pantheon-base/pantheon
    - pantheon-base/pantheon-files
    - pantheon-base/pantheon-greeter
    - pantheon-base/pantheon-settings
    - pantheon-base/pantheon-shell[-lightdm,-screensaver]
    - pantheon-base/plank
    - pantheon-base/screenshot-tool
    - pantheon-base/slingshot
    - pantheon-base/switchboard::elementary
    - pantheon-base/switchboard-plug-about::elementary
    - pantheon-base/switchboard-plug-accessibility::elementary
    - pantheon-base/switchboard-plug-applications::elementary
    - pantheon-base/switchboard-plug-bluetooth::elementary
    - pantheon-base/switchboard-plug-datetime::elementary
    - pantheon-base/switchboard-plug-display::elementary
    - pantheon-base/switchboard-plug-keyboard::elementary
    - pantheon-base/switchboard-plug-locale::elementary
    - pantheon-base/switchboard-plug-mouse-touchpad::elementary
    - pantheon-base/switchboard-plug-network::elementary
    - pantheon-base/switchboard-plug-notifications::elementary
    - pantheon-base/switchboard-plug-onlineaccounts::elementary
    - pantheon-base/switchboard-plug-pantheon-shell::elementary
    - pantheon-base/switchboard-plug-parental-controls::elementary
    - pantheon-base/switchboard-plug-power::elementary
    - pantheon-base/switchboard-plug-printers::elementary
    - pantheon-base/switchboard-plug-security-privacy::elementary
    - pantheon-base/switchboard-plug-sharing::elementary
    - pantheon-base/switchboard-plug-useraccounts::elementary
    - pantheon-base/wingpanel
    - pantheon-base/wingpanel-indicator-accessibility
    - pantheon-base/wingpanel-indicator-bluetooth
    - pantheon-base/wingpanel-indicator-datetime
    - pantheon-base/wingpanel-indicator-keyboard
    - pantheon-base/wingpanel-indicator-network
    - pantheon-base/wingpanel-indicator-notifications
    - pantheon-base/wingpanel-indicator-power
    - pantheon-base/wingpanel-indicator-session
    - pantheon-base/wingpanel-indicator-sound
