repository:
   description: Sabayon Community SCR
build:
  overlays:
    - wine-a-holics
    - activehome
    - and3k-sunrise
    - anyc
    - games-overlay
  target:
    - app-text/cherrytree::and3k-sunrise
    - games-strategy/megaglest::games-overlay
    - app-emulation/shashlik-bin::anyc
    - media-gfx/sweethome3d-bin::activehome
    - app-emulation/wine-staging::wine-a-holics
