repository:
   description: Sabayon Community SCR
build:
  emerge:
    # Install each package separately
    split_install: 1
  overlays:
    - activehome
    - and3k-sunrise
    - anyc
    - dev-zero
    - games-overlay
    - gamerlay
    - go-overlay
    - graaff
    - jorgicio
    - fuverlay
    - mrueg
    - ROKO__
    - science
    - sublime-text
    - y2kbadbug
  equo:
    package:
      install:
        - dev-libs/ocl-icd
  target:
    - app-editors/sublime-text::sublime-text
    - app-emulation/genymotion
    - app-emulation/shashlik-bin::anyc
    - app-eselect/eselect-sublime::sublime-text
    - app-misc/neofetch
    - app-text/cherrytree::and3k-sunrise
    - dev-libs/intel-beignet::mrueg
    - dev-util/eclipse-sdk-bin::jorgicio
    - games-fps/redeclipse::gamerlay
    - games-strategy/megaglest::games-overlay
    - media-gfx/sweethome3d-bin::activehome
    - media-sound/vkaudiosaver::ROKO__
    - media-tv/peerflix::jorgicio
    - net-im/qtox-bin
    - net-im/telegram-bin::fuverlay
    - net-misc/megasync::jorgicio
    - net-print/cloudprint::dev-zero
    - sci-libs/calculix-ccx::science
    - sci-libs/calculix-cgx::science
    - sys-fs/zfstools::graaff
    - www-apps/hugo::go-overlay
    - x11-misc/mugshot::y2kbadbug
    - x11-terms/altyo
