repository:
  description: Sabayon Community SCR

  maintenance:
    # clean_cache: 1

build:
  script:
    pre:
      - eselect profile set python3.6

  equo:
    package:
      install:
        - dev-libs/ocl-icd
  emerge:
    # Install each package separately
    split_install: 1
    preserved_rebuild: 1
    features: assume-digests binpkg-logs -userpriv config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync parallel-fetch preserve-libs protect-owned sandbox sfperms splitdebug strict
    remote_overlay:
      - flatpak-overlay|git|https://github.com/fosero/flatpak-overlay.git
      - np-hardass-overlay|git|https://github.com/NP-Hardass/np-hardass-overlay.git
      - sabayon-community|git|https://github.com/Sabayon/community.git
      - tlp|git|https://github.com/dywisor/tlp-portage.git
    overlays:
      - 4nykey
      - ace
      - activehome
      - and3k-sunrise
      - angelos
      - anyc
      - atom
      - backbone
      - bobwya
      - brother-overlay
      - c2p-overlay
      - cynede
      - didactic-duck
      - dlang
      - dev-zero
      - ephemeral
      - eva
      - fem-overlay
      - fkmclane
      - flavour
      - furikake
      - fw-overlay
      - gamerlay
      - gamerouns
      - games-overlay
      - gentoo-htpc
      - genealogy
      - go-overlay
      - graaff
      - hamper-overlay
      - haskell
      - ikelos
      - jm-overlay
      - jorgicio
      - jps-gentoo
      - jtriley
      - k_f
      - lmiphay
      - miramir
      - mozilla
      - mrueg
      - mv
      - oboeverlay
      - ohnobinki_overlay
      - pentoo
      - pinkpieea
      - poly-c
      - rasdark
      - redcore-desktop
      - rion
      - robbat2
      - roslin
      - scrill
      - salfter
      - sk-overlay
      - sinustrom
      - spikyatlinux
      - ssnb
      - steam-overlay
      - stefantalpalaru
      - stuff
      - sublime-text
      - swegener
      - tmacedo
      - trash
      - vortex
      - voyageur
      - weuxel
      - y2kbadbug
      - zugaina
  target:
    - app-admin/keepasshttp::np-hardass-overlay
    - app-arch/rarcrack::gerislay
    - app-crypt/veracrypt
    - app-editors/atom-bin::jorgicio
    - app-editors/brackets-bin
    - app-editors/sublime-text::sublime-text
    - app-editors/vscode::atom
    - app-emulation/remotebox::poly-c
    - app-eselect/eselect-sublime::sublime-text
    - app-laptop/tlp
    - app-misc/anki::sattvik
    - app-misc/double-commander-bin::rasdark
    - app-misc/gramps::genealogy
    - app-misc/neofetch
    - app-office/wps-office
    - app-text/cherrytree
    - app-text/gimagereader::salfter
    - app-text/gist
    - dev-db/etcd::gentoo
    - dev-embedded/arduino
    - dev-embedded/arduino-ide
    - dev-embedded/stlink::swegener
    - =dev-libs/intel-beignet-9999::mrueg
    - dev-tex/mimetex::k_f
    - dev-util/adobe-air-runtime::steam-overlay
    - dev-util/eclipse-sdk-bin::ssnb
    - dev-util/flatpak-builder::flatpak-overlay
    - dev-util/idea-community::ssnb
    - dev-util/phpstorm
    - dev-util/pdk::ace
    - dev-util/pycharm-community
    - dev-util/pycharm-professional
    - games-puzzle/osmos::gamerlay
    - games-strategy/megaglest
    - games-strategy/unknown-horizons::gamerlay
    - games-util/fteqcc-xonotic-9999::gamerlay
    - games-util/springlobby
    - kde-misc/nowdock-panel::lmiphay
    - media-gfx/brother-dcp145c-bin::brother-overlay
    - media-gfx/lightzone
    - media-gfx/pinta
    - media-gfx/sweethome3d-bin::activehome
    - media-gfx/ttfautohint::4nykey
    - media-sound/guitarix2::jorgicio
    - media-sound/lollypop::jorgicio
    - media-sound/pulseaudio-equalizer::zyrenth
    - media-sound/pulseeffects
    - media-sound/sox::gentoo
    - media-tv/peerflix::jorgicio
    - media-tv/plex-media-server
    - media-video/disper::fem-overlay
    - media-video/filebot::fkmclane
    - media-video/flowblade
    - net-im/hipchat::tmacedo
    - net-im/icq::vortex
    - net-im/skypeforlinux
    - net-im/slack::lmiphay
    - net-im/telegram-desktop-bin::gentoo
    - net-im/viber::calculate
    - net-im/zoom-bin::yurij-overlay
    - net-mail/davmail-bin::pentoo
    - net-misc/megasync
    - net-misc/mailru-cloud
    - =net-misc/gopenvpn-9999::np-hardass-overlay
    - net-misc/cjdns::weuxel
    - net-misc/gdrive::jm-overlay
    - net-misc/streamtuner2::stefantalpalaru
    - net-misc/screamingfrogseospider::jorgicio
    - net-print/brother-dcp1610w-bin::brother-overlay
    - net-print/brother-genml1-bin::brother-overlay
    - net-print/samsung-unified-linux-driver::pg_overlay
    - sci-geosciences/googleearth::mv
    - sys-apps/flatpak
    - sys-apps/sift::go-overlay
    - sys-app/xdg-desktop-portal::flatpak-overlay
    - sys-app/xdg-desktop-portal-gtk::flatpak-overlay
    - sys-cluster/kubectl
    - sys-cluster/minikube
    - sys-fs/libostree
    - sys-fs/zfstools::graaff
    - www-apps/hugo::go-overlay
    - www-client/brave-bin
    - www-client/palemoon-bin::palemoon
    - www-client/qutebrowser
    - x11-drivers/xf86-input-wizardpen::jorgicio
    - x11-libs/libvdpau-va-gl
    - x11-misc/iio-sensor-proxy
    - x11-misc/polybar
    - x11-misc/variety::pinkpieea
    - x11-terms/tilix::dlang
    - x11-wm/lumina
