repository:
   description: Sabayon Community SCR
build:
  emerge:
    # Install each package separately
    split_install: 1
  overlays:
    - activehome
    - and3k-sunrise
    - anyc
    - games-overlay
    - jorgicio
    - fuverlay
    - mrueg
    - science
  target:
    - net-im/telegram-bin::fuverlay
    - app-text/cherrytree::and3k-sunrise
    - games-strategy/megaglest::games-overlay
    - app-emulation/shashlik-bin::anyc
    - media-gfx/sweethome3d-bin::activehome
    - dev-util/eclipse-sdk-bin::jorgicio
    - dev-libs/intel-beignet::mrueg
    - sci-libs/calculix-cgx::science
    - sci-libs/calculix-ccx::science
