repository:
   description: Sabayon Community SCR
   maintenance:
     remove: 
       - app-emulation/wine-staging
build:
  overlays:
    - activehome
    - and3k-sunrise
    - anyc
    - games-overlay
    - jorgicio
    - fuverlay
    - stuff
  target:
    - net-im/telegram-bin::fuverlay
    - app-text/cherrytree::and3k-sunrise
    - games-strategy/megaglest::games-overlay
    - app-emulation/shashlik-bin::anyc
    - media-gfx/sweethome3d-bin::activehome
    - dev-util/eclipse-sdk-bin::jorgicio
    - sys-fs/google-drive-ocamlfuse::stuff
