repository:
  description: Sabayon Community SCR

  maintenance:
    # clean_cache: 1

build:
  equo:
    package:
      install:
        - dev-libs/ocl-icd
  emerge:
    # Install each package separately
    split_install: 1
    preserved_rebuild: 1
    remote_overlay:
      - flatpak-overlay|git|https://github.com/fosero/flatpak-overlay.git
      - np-hardass-overlay|git|https://github.com/NP-Hardass/np-hardass-overlay.git
      - sabayon-community|git|https://github.com/Sabayon/community.git
      - tlp|git|https://github.com/dywisor/tlp-portage.git
    overlays:
      - 4nykey
      - activehome
      - and3k-sunrise
      - angelos
      - anyc
      - backbone
      - belak
      - bobwya
      - brother-overlay
      - c2p-overlay
      - cynede
      - didactic-duck
      - dlang
      - dev-zero
      - ephemeral
      - eva
      - fem-overlay
      - fkmclane
      - flavour
      - furikake
      - gamerlay
      - gamerouns
      - games-overlay
      - gentoo-htpc
      - genealogy
      - go-overlay
      - graaff
      - hamper-overlay
      - ikelos
      - jm-overlay
      - jorgicio
      - jtriley
      - k_f
      - lmiphay
      - miramir
      - mozilla
      - mrueg
      - mv
      - oboeverlay
      - ohnobinki_overlay
      - pentoo
      - pinkpieea
      - poly-c
      - rasdark
      - redcore-desktop
      - rion
      - robbat2
      - roslin
      - salfter
      - sk-overlay
      - sinustrom
      - spikyatlinux
      - Spring
      - ssnb
      - steam-overlay
      - stefantalpalaru
      - stuff
      - sublime-text
      - swegener
      - tmacedo
      - trash
      - voyageur
      - weuxel
      - y2kbadbug
      - zugaina
  target:
    - app-admin/keepasshttp::np-hardass-overlay
    - app-arch/peazip
    - app-arch/rarcrack::robbat2
    - app-crypt/veracrypt
    - app-dicts/artha
    - app-editors/atom-bin::jorgicio
    - app-editors/brackets-bin
    - app-editors/scribes::belak
    - app-editors/sublime-text::sublime-text
    - app-emulation/RemoteBox::gentoo-htpc
    - app-eselect/eselect-sublime::sublime-text
    - app-laptop/tlp
    - app-misc/anki::sk-overlay
    - app-misc/double-commander
    - app-misc/gramps::genealogy
    - app-misc/neofetch
    - app-office/archi::flavour
    - app-office/fet
    - app-office/jstock::sinustrom
    - app-office/wps-office
    - app-text/cherrytree::and3k-sunrise
    - app-text/gimagereader::salfter
    - app-text/gist
    - app-text/simplenote
    - dev-db/etcd::gentoo
    - dev-embedded/arduino
    - dev-embedded/arduino-ide
    - dev-embedded/stlink::swegener
    - =dev-libs/intel-beignet-9999::mrueg
    - dev-tex/mimetex::k_f
    - dev-util/adobe-air-runtime::steam-overlay
    - dev-util/eclipse-sdk-bin::jorgicio
    - dev-util/flatpak-builder::flatpak-overlay
    - dev-util/idea-community::ssnb
    - dev-util/phpstorm
    - dev-util/pycharm-community
    - dev-util/pycharm-professional
    - games-fps/redeclipse
    - games-puzzle/osmos::gamerlay
    - games-sports/maniadrive-bin::zugaina
    - games-strategy/megaglest
    - games-strategy/unknown-horizons::gamerlay
    - games-strategy/zod-engine
    - games-util/fteqcc-xonotic-9999::gamerlay
    - games-util/springlobby::Spring
    - games-util/wiithon::LocalOverlay
    - gnome-extra/gnome-encfs::gentoo
    - kde-misc/nowdock-panel::lmiphay
    - media-gfx/brother-dcp145c-bin::brother-overlay
    - media-gfx/lightzone
    - media-gfx/phatch::jtriley
    - media-gfx/pinta
    - media-gfx/sweethome3d-bin::activehome
    - media-gfx/ttfautohint::4nykey
    - media-sound/guitarix2::jorgicio
    - media-sound/lollypop::jorgicio
    - media-sound/pulseaudio-equalizer::zyrenth
    - media-sound/pulseeffects
    - media-sound/sox::gentoo
    - media-tv/peerflix::jorgicio
    - media-tv/plex-media-server
    - media-video/disper
    - media-video/filebot
    - media-video/flowblade
    - net-im/hipchat::tmacedo
    - net-im/qtox
    - net-im/skypeforlinux
    - net-im/slack::lmiphay
    - net-im/telegram-desktop-bin::gentoo
    - net-im/zoom-bin::yurij-overlay
    - net-mail/davmail-bin::pentoo
    - net-misc/megasync
    - =net-misc/gopenvpn-9999::np-hardass-overlay
    - net-misc/cjdns::weuxel
    - net-misc/streamtuner2::stefantalpalaru
    - net-misc/screamingfrogseospider::jorgicio
    - net-print/brother-dcp1610w-bin::brother-overlay
    - net-print/brother-genml1-bin::brother-overlay
    - net-print/samsung-unified-linux-driver::ohnobinki_overlay
    - sci-geosciences/googleearth
    - sys-apps/flatpak
    - sys-apps/sift::go-overlay
    - sys-app/xdg-desktop-portal
    - sys-app/xdg-desktop-portal-gtk
    - sys-cluster/kubectl
    - sys-cluster/minikube
    - sys-fs/libostree
    - sys-fs/zfstools::graaff
    - www-apps/hugo::go-overlay
    - www-client/palemoon-bin::palemoon
    - x11-drivers/wizardpen
    - x11-libs/libvdpau-va-gl
    - x11-misc/iio-sensor-proxy
    - x11-misc/polybar
    - x11-terms/tilix::dlang
    - x11-wm/lumina
