repository:
   description: Sabayon Community SCR
build:
  emerge:
    # Install each package separately
    split_install: 1
    remote_overlay:
      - rsync://gentoo.zugaina.org/bgo-overlay
  overlays:
    - activehome
    - and3k-sunrise
    - anyc
    - belak
    - c2p-overlay
    - dev-zero
    - eva
    - flavour
    - furikake
    - fw-overlay
    - games-overlay
    - gamerlay
    - gentoo-htpc
    - go-overlay
    - graaff
    - jorgicio
    - fuverlay
    - k_f
    - mozilla
    - mrueg
    - ohnobinki_overlay
    - robbat2
    - ROKO__
    - roslin
    - Spring
    - stefantalpalaru
    - sublime-text
    - tmacedo
    - vortex
    - weuxel
    - y2kbadbug
    - zugaina
  equo:
    package:
      install:
        - dev-libs/ocl-icd
  target:
    - app-arch/peazip::c2p-overlay
    - app-arch/rarcrack::robbat2
    - app-dicts/artha
    - app-editors/gedit-latex::eva
    - app-editors/scribes::belak
    - app-editors/sublime-text::sublime-text
    - app-emulation/genymotion
    - app-emulation/RemoteBox::gentoo-htpc
    - app-emulation/shashlik-bin::anyc
    - app-eselect/eselect-sublime::sublime-text
    - app-misc/fet
    - app-misc/neofetch
    - app-office/archi::flavour
    - app-text/cherrytree::and3k-sunrise
    - dev-libs/intel-beignet::mrueg
    - dev-tex/mimetex::k_f
    - dev-util/eclipse-sdk-bin::jorgicio
#    - dev-util/idea::fw-overlay http://scrinfra.sabayonlinux.org/logs/2016-05-14/community.1463189666.log hide until https://github.com/Sabayon/entropy/commit/67a645fabe4dcc99a63c7999eaf989cfbc11de51 gets into an entropy release
    - games-arcade/sdl-ball::roslin
    - games-fps/redeclipse::gamerlay
    - games-puzzle/osmos::gamerlay
    - games-simulation/vegastrike::vortex
    - games-sports/maniadrive-bin::zugaina
    - games-strategy/megaglest::games-overlay
    - games-strategy/unknown-horizons::gamerlay
    - games-strategy/zod-engine::games-overlay
    - games-util/springlobby::Spring
    - media-gfx/lightzone
    - media-gfx/sweethome3d-bin::activehome
    - media-sound/guitarix2::jorgicio
    - media-sound/nuvolaplayer::furikake
    - media-sound/vkaudiosaver::ROKO__
    - media-tv/peerflix::jorgicio
    - net-im/hipchat::tmacedo
    - net-im/qtox-bin
    - net-im/telegram-bin::fuverlay
    - net-misc/megasync::jorgicio
    - net-misc/cjdns::weuxel
    - net-misc/streamtuner2::stefantalpalaru
    - net-print/cloudprint::dev-zero
    - net-print/samsung-unified-linux-driver::ohnobinki_overlay
    - sys-apps/sift::go-overlay
    - sys-fs/zfstools::graaff
    - www-apps/hugo::go-overlay
    - x11-misc/mugshot::y2kbadbug
    - x11-terms/altyo
