repository:
   description: Sabayon Community SCR
build:
  emerge:
    # Install each package separately
    split_install: 1
  overlays:
    - activehome
    - and3k-sunrise
    - anyc
    - games-overlay
    - gamerlay
    - jorgicio
    - fuverlay
    - mrueg
    - ROKO__
    - science
    - sublime-text
    - y2kbadbug
  equo:
    package:
      install:
        - dev-libs/ocl-icd
      mask:
        - www-client/w3m::sabayonlinux.org
  target:
    - net-im/telegram-bin::fuverlay
    - app-text/cherrytree::and3k-sunrise
    - games-strategy/megaglest::games-overlay
    - app-emulation/shashlik-bin::anyc
    - media-gfx/sweethome3d-bin::activehome
    - dev-util/eclipse-sdk-bin::jorgicio
    - dev-libs/intel-beignet::mrueg
    - sci-libs/calculix-cgx::science
    - sci-libs/calculix-ccx::science
    - app-editors/sublime-text::sublime-text
    - app-eselect/eselect-sublime::sublime-text
    - media-sound/vkaudiosaver::ROKO__
    - media-tv/peerflix::jorgicio
    - x11-misc/mugshot::y2kbadbug
    - games-fps/redeclipse::gamerlay
    - app-misc/neofetch
