repository:
   description: Sabayon Community SCR
build:
  emerge:
    # Install each package separately
    split_install: 1
  overlays:
    - activehome
    - and3k-sunrise
    - anyc
    - belak
    - bgo-overlay
    - c2p-overlay
    - dev-zero
    - eva
    - furikake
    - fw-overlay
    - games-overlay
    - gamerlay
    - go-overlay
    - graaff
    - jorgicio
    - fuverlay
    - k_f
    - mrueg
    - robbat2
    - ROKO__
    - roslin
    - sublime-text
    - tmacedo
    - vortex
    - weuxel
    - y2kbadbug
  equo:
    package:
      install:
        - dev-libs/ocl-icd
  target:
    - app-arch/peazip::c2p-overlay
    - app-arch/rarcrack::robbat2
    - app-dicts/artha::bgo-overlay
    - app-editors/gedit-latex::eva
    - app-editors/scribes::belak
    - app-editors/sublime-text::sublime-text
    - app-emulation/genymotion
    - app-emulation/shashlik-bin::anyc
    - app-eselect/eselect-sublime::sublime-text
    - app-misc/fet::bgo-overlay
    - app-misc/neofetch
    - app-text/cherrytree::and3k-sunrise
    - dev-libs/intel-beignet::mrueg
    - dev-tex/mimetex::k_f
    - dev-util/eclipse-sdk-bin::jorgicio
    - dev-util/idea::fw-overlay
    - games-arcade/sdl-ball::roslin
    - games-fps/redeclipse::gamerlay
    - games-puzzle/osmos::gamerlay
    - games-simulation/vegastrike::vortex
    - games-strategy/megaglest::games-overlay
    - media-gfx/sweethome3d-bin::activehome
    - media-sound/guitarix2::jorgicio
    - media-sound/nuvolaplayer::furikake
    - media-sound/vkaudiosaver::ROKO__
    - media-tv/peerflix::jorgicio
    - net-im/hipchat::tmacedo
    - net-im/qtox-bin
    - net-im/telegram-bin::fuverlay
    - net-misc/megasync::jorgicio
    - net-misc/cjdns::weuxel
    - net-print/cloudprint::dev-zero
    - sys-apps/sift::go-overlay
    - sys-fs/zfstools::graaff
    - www-apps/hugo::go-overlay
    - x11-misc/mugshot::y2kbadbug
    - x11-terms/altyo
