repository:
   description: mudler's repository
   maintenance:
     remove:
       - www-apps/gogs
build:
  emerge:
    # Install each package separately
    split_install: 1
  overlays:
    - go-overlay
  target:
    - www-apps/gogs::go-overlay
    - app-shells/peco::go-overlay
    - app-shells/antibody::go-overlay
    - dev-go/gox::go-overlay
    - dev-go/goxc::go-overlay
    - dev-go/ffjson::go-overlay
    - net-misc/bat::go-overlay
    - net-p2p/cloud-torrent::go-overlay
    - x11-misc/noti::go-overlay
    - www-apps/gotty::go-overlay
    - dev-go/go-bindata::go-overlay
