repository:
   description: Pentesting repository
   maintenance:
     remove:
       - net-wireless/btscanner
build:
  emerge:
    # Install each package separately
    split_install: 1
    features: assume-digests binpkg-logs compressdebug config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync news parallel-fetch preserve-libs protect-owned sandbox sfperms splitdebug strict unknown-features-warn unmerge-logs unmerge-orphans userfetch usersandbox usersync xattr userpriv
  overlays:
    - pentoo
  equo:
    package:
      install:
        - dev-ruby/timers:4
  target:
    - net-analyzer/dnsrecon::pentoo
    - net-analyzer/etherape::pentoo
    - net-analyzer/sslyze::pentoo
    - net-analyzer/ipv6-toolkit::pentoo
    - net-analyzer/aimsniff::pentoo
    - app-fuzz/bss::pentoo
    - net-wireless/bt-audit::pentoo
    - net-wireless/crackle::pentoo
    - net-wireless/kismet-ubertooth::pentoo
    - app-exploits/weevely::pentoo
    - net-wireless/wifite::pentoo
    - net-analyzer/bettercap # from local overlay
    - dev-db/sqlmap::pentoo
    - net-proxy/zaproxy::pentoo
    - net-analyzer/sslyze::pentoo
    - net-analyzer/recon-ng::pentoo
    - net-wireless/cowpatty::pentoo
    - net-wireless/wifitap::pentoo
    - net-misc/tcpick::pentoo
    - app-antivirus/malheur::pentoo
    - app-crypt/steghide::pentoo
    - app-fuzz/dotdotpwn::pentoo
    - dev-util/radare2::pentoo
    - net-analyzer/inguma::pentoo
    - net-analyzer/w3af::pentoo
    - net-analyzer/yersinia::pentoo
    - www-apps/beef::pentoo
    - net-analyzer/set::pentoo
    - net-analyzer/armitage-bin::pentoo
    - app-forensics/inception::pentoo
