repository:
   description: Pentesting repository
   maintenance:
     remove:
       - net-wireless/btscanner
build:
  emerge:
    # Install each package separately
    split_install: 1
  overlays:
    - pentoo
  target:
    - net-analyzer/dnsrecon::pentoo
    - net-analyzer/etherape::pentoo
    - net-analyzer/sslyze::pentoo
    - net-analyzer/ipv6-toolkit::pentoo
    - net-analyzer/aimsniff::pentoo
    - net-analyzer/snmpenum::pentoo
    - app-fuzz/bss::pentoo
    - net-wireless/bt-audit::pentoo
    - net-wireless/btscanner::pentoo
    - net-wireless/crackle::pentoo
    - net-wireless/kismet-ubertooth::pentoo
    - app-exploits/weevely::pentoo
    - net-wireless/wifite::pentoo
    - net-analyzer/bettercap::pentoo
    - dev-db/sqlmap::pentoo
    - net-proxy/zaproxy::pentoo
    - net-analyzer/sslyze::pentoo
    - net-analyzer/recon-ng::pentoo
