repository:
   description: Gaming live repository
build:
  emerge:
    # Install each package separately
    split_install: 1
    default_args: --accept-properties=-interactive -t --verbose --nospinner --oneshot --complete-graph --buildpkg
  overlays:
    - farmboy0 
    - oiledmachine
    - steam-overlay
  target:
    - sys-kernel/dkms::netcrave
    - sys-kernel/amdgpu-pro-dkms
    - x11-drivers/amdgpu-pro
    - =media-libs/mesa-9999
    - =sys-devel/llvm-9999::gentoo
    - =x11-libs/libdrm-9999
    - games-util/steam-meta::steam-overlay
