repository:
   description: Gaming live repository
build:
  emerge:
    # Install each package separately
    split_install: 1
    default_args: --accept-properties=-interactive -t --verbose --nospinner --oneshot --complete-graph --buildpkg
  target:
    - =media-libs/mesa-9999
    - =x11-libs/libdrm-9999
