repository:
   description: Gaming live repository
   maintenance:
     clean_cache: 1
build:
  emerge:
    # Install each package separately
    split_install: 1
    default_args: --accept-properties=-interactive -t --verbose --nospinner --oneshot --complete-graph --buildpkg
    features: assume-digests binpkg-logs -userpriv config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync parallel-fetch preserve-libs protect-owned sandbox sfperms splitdebug strict
  overlays:
  target:
    - =sys-devel/clang-7.0.0_rc3[doc]::gentoo
    - =sys-devel/clang-runtime-7.0.0_rc3::gentoo
    - =sys-libs/compiler-rt-7.0.0_rc3::gentoo
    - =sys-libs/compiler-rt-sanitizers-7.0.0_rc3::gentoo
    - =sys-devel/llvm-7.0.0_rc3[doc]::gentoo
    - =media-libs/mesa-18.2.0-r1::gentoo
