repository:
  description: Sihnon common packages

  #maintenance:
  #  clean_cache: 1

build:
  script:
    pre:
      - eselect python set python3.5

  emerge:
    # Install each package separately
    split_install: 1
    preserved_rebuild: 1

  equo:
    dependency_install:
      prune_virtuals: 1

  # Use ebuilds from the following layman overlays
  overlays:
    - fkmclane
    - frabjous
    - gentoo-zh
    - hacking-gentoo
    - sihnon
    - swegener

  # Packages to be built in this repo
  target:
    - app-admin/collectd
    - app-admin/logstash-bin
    - app-crypt/dehydrated
    - app-admin/consul
    - app-admin/lastpass-cli
    - app-admin/librarianp::sihnon
    - app-admin/librarian-puppet::sihnon
    - app-admin/mcollective::gentoo
    #- app-admin/puppet-agent::gentoo
    - app-admin/puppet-lint::gentoo
    - app-admin/vault
    - app-vim/puppet-syntax::gentoo
    - dev-libs/sihnon-php-lib::sihnon
    - dev-libs/sihnon-js-lib::sihnon
    - dev-perl/Monitoring-Plugin
    - dev-python/django-haystack::gentoo
    - dev-ruby/hiera-eyaml-gpg::gentoo
    - dev-ruby/hiera-puppet-helper::sihnon
    - dev-ruby/jerakia
    - dev-ruby/puppet-syntax::sihnon
    - dev-ruby/puppet_forge::sihnon
    - dev-ruby/puppetdb-termini
    - dev-ruby/puppetlabs_spec_helper::sihnon
    - dev-ruby/rspec-puppet::sihnon
    - dev-ruby/rspec-puppet-utils::sihnon
    - dev-ruby/simplecov::gentoo
    - dev-ruby/simplecov-html::gentoo
    - dev-ruby/simplecov-rcov::sihnon
    - dev-util/jenkins-bin::gentoo
    - dev-vcs/vcsh::gentoo
    - mcollective-plugin/mcollective-actionpolicy-auth-master::hacking-gentoo
    - mcollective-plugin/mcollective-plugin-update-system::hacking-gentoo
    - mcollective-plugin/mcollective-puppet-agent::sihnon
    - mcollective-plugin/mcollective-puppetca-agent::sihnon
    - mcollective-plugin/mcollective-puppetenvsh-agent::sihnon
    - mcollective-plugin/mcollective-service-agent-master::hacking-gentoo
    - media-tv/tvheadend
    - media-tv/xmltv
    - net-analyzer/nagios-plugins::gentoo
    - net-analyzer/nagios-plugin-check-scsi-smart
    - net-dns/hash-slinger
    # Blocked by media-video/subliminal-0.7.4. Needs bumping to 1.1.1 which eliminates the
    # need to mask babelfish and guessit
    #- net-misc/flexget::sihnon
    - net-misc/lldpd::gentoo
    - net-misc/openssh::gentoo
    - net-misc/pssh::gentoo
    - net-wireless/rtl-sdr::gentoo
    - sys-apps/fwupd::gentoo
    - sys-apps/fwupdate::gentoo
    - sys-auth/google-authenticator::gentoo
    - sys-auth/sssd
    - sys-fs/zfs-auto-snapshot::gentoo-zh

# vim: set ts=2 shiftwidth=2 expandtab :
