repository:
  description: Sihnon common packages

build:
  emerge:
    # Install each package separately
    split_install: 1

    # Use sihnon overlay
    remote_overlay: https://github.com/optiz0r/gentoo-overlay.git

  equo:
    package:
      remove:
        # These packages conflict with puppet-agent
        - app-admin/puppet
        - app-emulation/virt-what
        - dev-ruby/facter
        - dev-ruby/hiera

  # Use ebuilds from the following layman overlays
  overlays:
    - gentoo-zh
    - hacking-gentoo
    - swegener

  # Packages to be built in this repo
  target:
    - app-admin/lastpass-cli
    - app-admin/librarian-puppet::sihnon
    - app-admin/puppet-agent::gentoo
    - app-admin/puppet-lint::gentoo
    - app-vim/puppet-syntax::gentoo
    - dev-libs/sihnon-php-lib::sihnon
    - dev-libs/sihnon-js-lib::sihnon
    - dev-python/django-haystack::gentoo
    - dev-ruby/hiera-eyaml-gpg::gentoo
    - dev-ruby/hiera-puppet-helper::sihnon
    - dev-ruby/puppet-syntax::sihnon
    - dev-ruby/puppet_forge::sihnon
    - dev-ruby/puppetlabs_spec_helper::sihnon
    - dev-ruby/rspec-puppet::sihnon
    - dev-ruby/rspec-puppet-utils::sihnon
    - dev-ruby/simplecov::gentoo
    - dev-ruby/simplecov-html::gentoo
    - dev-ruby/simplecov-rcov::sihnon
    - dev-util/jenkins-bin::gentoo
    - dev-vcs/vcsh::gentoo
    - mcollective-plugin/mcollective-actionpolicy-auth-master::hacking-gentoo
    - mcollective-plugin/mcollective-plugin-update-system::hacking-gentoo
    - mcollective-plugin/mcollective-puppet-agent::sihnon
    - mcollective-plugin/mcollective-puppetca-agent::sihnon
    - mcollective-plugin/mcollective-puppetenvsh-agent::sihnon
    - mcollective-plugin/mcollective-service-agent-master::hacking-gentoo
    - media-tv/tvheadend
    - media-tv/xmltv
    - net-analyzer/nagios-plugins::gentoo
    # Blocked by media-video/subliminal-0.7.4. Needs bumping to 1.1.1 which eliminates the
    # need to mask babelfish and guessit
    #- net-misc/flexget::sihnon
    - net-misc/openssh::gentoo
    - net-misc/pssh::gentoo
    - sys-auth/google-authenticator::gentoo
    - sys-auth/nss_ldap::gentoo
    - sys-auth/nss_updatedb::swegener
    #- sys-auth/pam_ccreds::barzog-overlay
    - sys-auth/pam_ldap::gentoo
    - sys-fs/zfs-auto-snapshot::gentoo-zh

# vim: set ts=2 shiftwidth=2 expandtab :
