repository:
  description: Sihnon desktop packages

  remove:
      # Available in sabayonlinux.org
    - sys-auth/ykpers

build:
  emerge:
    # Install each package separately
    split_install: 1

    # Use sihnon overlay
    remote_overlay: https://github.com/optiz0r/gentoo-overlay.git

  # Use ebuilds from the following layman overlays
  overlays:
    - jkolo

  # Packages to be built in this repo
  target:
    - app-crypt/yubico-piv-tool
    - app-crypt/yubikey-neo-manager
    - app-crypt/yubikey-piv-manager

# vim: set ts=2 shiftwidth=2 expandtab :
