repository:
   description: Spike Pentesting repository
build:
  emerge:
    # Install each package separately
    split_install: 1
  overlays:
    - spike
  target:
    - spike/spike-pentesting::spike
