repository:
   description: Spike Pentesting repository
build:
  emerge:
    # Install each package separately
    split_install: 1
  overlays:
    - spike
  target:
    - spike/spike-pentesting::spike
    - app-antivirus/malheur::spike
    - app-cdr/dumpet::spike
    - app-crypt/SIPcrack::spike
    - app-crypt/WiRouterKeyRec::spike
    - app-crypt/asleap::spike
    - app-crypt/cpyrit_cuda::spike
    - app-crypt/hashkill::spike
    - app-crypt/oclhashcat-plus-bin::spike
    - app-crypt/pyrit::spike
    - app-crypt/rcracki_mt::spike
    - app-crypt/samdump2::spike
    - app-crypt/steghide::spike
    - app-dicts/raft-wordlists::spike
    - app-emulation/virt-viewer::spike
    - app-exploits/exploitdb::spike
    - app-exploits/shellstorm::spike
    - app-exploits/weevely::spike
    - app-forensics/dff::spike
    - app-forensics/disitool::spike
    - app-forensics/inception::spike
    - app-forensics/libforensic1394::spike
    - app-forensics/libpff::spike
    - app-forensics/libvshadow::spike
    - app-forensics/make-pdf::spike
    - app-forensics/pdf-parser::spike
    - app-forensics/pdfid::spike
    - app-forensics/streams::spike
    - app-forensics/tcpxtract::spike
    - app-forensics/volatility::spike
    - app-forensics/yara::spike
    - app-forensics/yim2text::spike
    - app-fuzz/Peach::spike
    - app-fuzz/bed::spike
    - app-fuzz/bss::spike
    - app-fuzz/dotdotpwn::spike
    - app-fuzz/fuzzdb::spike
    - app-fuzz/fuzzer-server::spike
    - app-fuzz/http-fuzz::spike
    - app-fuzz/ohrwurm::spike
    - app-fuzz/slowhttptest::spike
    - app-fuzz/smtp-fuzz::spike
    - app-i18n/scim::spike
    - app-misc/crunch::spike
    - app-misc/ddate::spike
    - app-misc/dradis::spike
    - app-misc/libmsr::spike
    - dev-db/minimysqlator::spike
    - dev-db/mssqlscan::spike
    - dev-db/oat::spike
    - dev-db/sqlbf::spike
    - dev-db/sqlibf::spike
    - dev-db/sqlix::spike
    - dev-db/sqlmap::spike
    - dev-db/sqlsus::spike
    - dev-db/themole::spike
    - dev-util/apktool::spike
    - dev-util/ati-app-sdk-bin::spike
    - dev-util/bokken::spike
    - dev-util/capstone::spike
    - dev-util/dex2jar::spike
    - dev-util/radare2::spike
    - net-analyzer/armitage::spike
    - net-analyzer/arpantispoofer::spike
    - net-analyzer/bro::spike
    - net-analyzer/cisco-auditing-tool::spike
    - net-analyzer/cisco-bruteforce-enabler::spike
    - net-analyzer/cisco-scanner::spike
    - net-analyzer/cisco-torch::spike
    - net-analyzer/davtest::spike
    - net-analyzer/dnsa::spike
    - net-analyzer/dnsrecon::spike
    - net-analyzer/dnsenum::spike
    - net-analyzer/enum4linux::spike
    - net-analyzer/evilgrade::spike
    - net-analyzer/fierce::spike
    - net-analyzer/geoedge::spike
    - net-analyzer/geoipgen::spike
    - net-analyzer/httprint::spike
    - net-analyzer/hyenae::spike
    - net-analyzer/inguma::spike
    - net-analyzer/jmsdigger-bin::spike
    - net-analyzer/loki::spike
    - net-analyzer/maketh::spike
    - net-analyzer/masscan::spike
    - net-analyzer/nacker::spike
    - net-analyzer/netmap::spike
    - net-analyzer/nmap_vulscan::spike
    - net-analyzer/ntp-fingerprint::spike
    - net-analyzer/onesixtyone::spike
    - net-analyzer/padbuster::spike
    - net-analyzer/plecost::spike
    - net-analyzer/polenum::spike
    - net-analyzer/post-it-dos::spike
    - net-analyzer/ppscan::spike
    - net-analyzer/recon-ng::spike
    - net-analyzer/rpcapd::spike
    - net-analyzer/sessionlist::spike
    - net-analyzer/set::spike
    - net-analyzer/sipvicious::spike
    - net-analyzer/smtpmap::spike
    - net-analyzer/snmpenum::spike
    - net-analyzer/sqlninja::spike
    - net-analyzer/sslcat::spike
    - net-analyzer/sslscan::spike
    - net-analyzer/sslstrip::spike
    - net-analyzer/ssltest::spike
    - net-analyzer/sslyze::spike
    - net-analyzer/subdomainer::spike
    - net-analyzer/suricata::spike
    - net-analyzer/thc-pptp-bruter::spike
    - net-analyzer/thc-ssl-dos::spike
    - net-analyzer/theHarvester::spike
    - net-analyzer/upnpwn::spike
    - net-analyzer/voiphopper::spike
    - net-analyzer/vomit::spike
    - net-analyzer/waffit::spike
    - net-analyzer/wapiti::spike
    - net-analyzer/w3af::spike
    - net-analyzer/webshag::spike
    - net-analyzer/wfuzz::spike
    - net-analyzer/wolpertinger::spike
    - net-analyzer/wpscan::spike
    - net-analyzer/xplico::spike
    - net-analyzer/zarp::spike
    - net-fs/afpfs-ng::spike
    - net-misc/badvpn::spike
    - net-misc/bdfactory::spike
    - net-misc/brutessh::spike
    - net-misc/edgessh::spike
    - net-misc/f5vpn-login::spike
    - net-misc/faifa::spike
    - net-misc/fwknop::spike
    - net-misc/karma::spike
    - net-misc/mitmf::spike
    - net-misc/ngrok::spike
    - net-misc/rdesktop-brute::spike
    - net-misc/sipp::spike
    - net-misc/httpfs::spike
    - net-misc/sslh::spike
    - net-misc/t50::spike
    - net-misc/tcpick::spike
    - net-misc/voipong::spike
    - net-misc/wlan2eth::spike
    - net-proxy/3proxy::spike
    - net-proxy/burpsuite::spike
    - net-proxy/hosproxy::spike
    - net-proxy/mitmproxy::spike
    - net-proxy/pbounce::spike
    - net-proxy/proxystrike::spike
    - net-proxy/pwnat::spike
    - net-proxy/redsocks::spike
    - net-proxy/sshttp::spike
    - net-proxy/zaproxy::spike
    - net-wireless/bt-audit::spike
    - net-wireless/btscanner::spike
    - net-wireless/bully::spike
    - net-wireless/cowpatty::spike
    - net-wireless/fern-wifi-cracker::spike
    - net-wireless/grimwepa::spike
    - net-wireless/haraldscan::spike
    - net-wireless/horst::spike
    - net-wireless/karmetasploit::spike
    - net-wireless/killerbee::spike
    - net-wireless/mfoc::spike
    - net-wireless/morse2txt::spike
    - net-wireless/rfidtool::spike
    - net-wireless/virtualradar-bin::spike
    - net-wireless/wifite::spike
    - spike/spike-pentesting-menu::spike
    - sys-apps/become::spike
    - www-misc/xsser::spike
